### ISSUE TITLE
Viooz playback BROKEN - Plays advertisement audio - No video.

### ISSUE THREAD

**Issue by flaillomanz** [pixeltailgames/cinema#79]
Viooz playback is broken - When I request the URL, it just displays an image of the webpage as it appears in the request menu.
![2014-12-03_00001](https://cloud.githubusercontent.com/assets/8304910/5281076/27da4a1e-7b34-11e4-9c67-413c8cec2e3e.jpg)
Due to this, the video player is cut off and the movie never starts playing.
As soon as I load the video page in the *requests* menu, before I've even told it to request the URL, there's a bucketload of ads loaded, and one really obnoxious "make money fast" ad starts playing (audio only) and will not shut up until I physically exit the game.

**Comment by Taset5** [comment]
Since there is no response on this one I will just comment here.

The video getting cut off and never playing is (probably) due to the ads some video players place on top of their videos. Since you can't use your mouse to click past the ads the cinema gets stuck on them. Its probably not very plausable, but integration with adblock or some similar service would be nice.

The ads playing in the background are something I'm all too familiar with. They do in fact require you to restart Gmod entirely for them to shut down. Since Viooz is really loaded with ads, they end up in multiple tabs on normal browsers, but since the cinema browser doesn't allow for other tabs there is no way (at least not that I know) of finding the ads and closing them manually. To avoid this I would recommend alt+tabbing to your own browser and finding the movie there, copying the URL, and pasting it into the cinema chat. This will allow you to easily shut down any obnoxious ads that popup. Again, adblock would be great for the cinema browser.

**Comment by samuelmaddock** [comment]
While adblock might be a nice thing to have, Chrome extensions won't work directly with Awesomium. Creating and maintaining my own version of it just for Cinema isn't worth it in my opinion. The problem with ads popping up in the background of Garry's Mod is outside of my control and will likely never be fixed due to the lack of developers working on the game.

As for the issues with Viooz playback, the original service was implemented over a year ago and since that time parts of Viooz has changed. There are now several different video players on the page which each have their own Adobe Flash JavaScript interfaces (or lack of one). Viooz offers no public API, rightfully so, which makes integrating this service a hack. Unfortunately, I don't think continuing to support this service is something I want to invest time into. Especially due to how volatile it is, there's no telling when it will be shutdown or change.

If @WinterPhoenix96 is able to fix the service (see #84), I'll gladly merge the changes. However, I'm not too optimistic that there is a good solution to the problem.
