### ISSUE TITLE
In-Game Browser Sometimes Doesn't Update URL

### ISSUE THREAD

**Issue by swamponions** [pixeltailgames/cinema#93]
There's an annoying intermittent problem with the built-in video requesting browser.

So, you hold Q, click Request Video, and click on youtube, and then youtube opens up, and the url in the browser reads "youtube.com." Then you search for something, and the url reads "youtube.com/results?...", and then you click a video, and the url updates to "youtube.com/watch?..." and the Request URL button turns red and you request it, right?

Except sometimes the URL doesn't update. This is really frustrating when you're trying to request a youtube video and the address bar still reads "youtube.com/results?..." and you can't request it because the game doesn't think it's a valid url. This happens to me intermittently - no idea what might be causing it.

**Comment by samuelmaddock** [comment]
I've noticed this as well, I'll try taking a look at it tonight.
On May 15, 2015 5:29 AM, "swamponions" <notifications@github.com> wrote:
>
> There's an annoying intermittent problem with the built-in video
requesting browser.
>
> So, you hold Q, click Request Video, and click on youtube, and then
youtube opens up, and the url in the browser reads "youtube.com." Then you
search for something, and the url reads "youtube.com/results?...", and then
you click a video, and the url updates to "youtube.com/watch?..." and the
Request URL button turns red and you request it, right?
>
> Except sometimes the URL doesn't update. This is really frustrating when
you're trying to request a youtube video and the address bar still reads "
youtube.com/results?..." and you can't request it because the game doesn't
think it's a valid url. This happens to me intermittently - no idea what
might be causing it.

**Comment by samuelmaddock** [comment]
The browser panels will now poll the webpage every second to detect if the URL has changed. This seems to have better results than what happened before.
